import { MD3DarkTheme, MD3LightTheme } from "react-native-paper";

export const themeLight = {
    ...MD3LightTheme,
    colors: {
        ...MD3LightTheme.colors,
        "primary": "#415F91",
        "surfaceTint": "#415F91",
        "onPrimary": "#FFFFFF",
        "primaryContainer": "#D6E3FF",
        "onPrimaryContainer": "#274777",
        "secondary": "#30628C",
        "onSecondary": "#FFFFFF",
        "secondaryContainer": "#CFE5FF",
        "onSecondaryContainer": "#104A73",
        "tertiary": "#705575",
        "onTertiary": "#FFFFFF",
        "tertiaryContainer": "#FAD8FD",
        "onTertiaryContainer": "#573E5C",
        "error": "#BA1A1A",
        "onError": "#FFFFFF",
        "errorContainer": "#FFDAD6",
        "onErrorContainer": "#93000A",
        "background": "#F9F9FF",
        "onBackground": "#191C20",
        "surface": "#F9F9FF",
        "onSurface": "#191C20",
        "surfaceVariant": "#E0E2EC",
        "onSurfaceVariant": "#44474E",
        "outline": "#74777F",
        "outlineVariant": "#C4C6D0",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#2E3036",
        "inverseOnSurface": "#F0F0F7",
        "inversePrimary": "#AAC7FF",
        "primaryFixed": "#D6E3FF",
        "onPrimaryFixed": "#001B3E",
        "primaryFixedDim": "#AAC7FF",
        "onPrimaryFixedVariant": "#274777",
        "secondaryFixed": "#CFE5FF",
        "onSecondaryFixed": "#001D33",
        "secondaryFixedDim": "#9CCBFB",
        "onSecondaryFixedVariant": "#104A73",
        "tertiaryFixed": "#FAD8FD",
        "onTertiaryFixed": "#28132E",
        "tertiaryFixedDim": "#DCBCE0",
        "onTertiaryFixedVariant": "#573E5C",
        "surfaceDim": "#D9D9E0",
        "surfaceBright": "#F9F9FF",
        "surfaceContainerLowest": "#FFFFFF",
        "surfaceContainerLow": "#F3F3FA",
        "surfaceContainer": "#EDEDF4",
        "surfaceContainerHigh": "#E7E8EE",
        "surfaceContainerHighest": "#E2E2E9",
        "statusPlanned": "#999999",
        "statusPaid": "#67B533",
        "statusDone": "#EAAB00",
        "onStatusPlanned": "#111111",
        "onStatusPaid": "#DDDDDD",
        "onStatusDone": "#DDDDDD"
    }
}

export const themeDark = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        "primary": "#D3BCFD",
        "surfaceTint": "#D3BCFD",
        "onPrimary": "#38265C",
        "primaryContainer": "#4F3D74",
        "primaryDisabled": "#2D1B52",
        "onPrimaryContainer": "#EBDDFF",
        "onPrimaryDisabled": "#EBDDFF",
        "secondary": "#CDC2DB",
        "onSecondary": "#342D40",
        "secondaryContainer": "#4B4358",
        "onSecondaryContainer": "#E9DEF8",
        "tertiary": "#F0B7C5",
        "onTertiary": "#4A2530",
        "tertiaryContainer": "#643B46",
        "onTertiaryContainer": "#FFD9E1",
        "error": "#FFB4AB",
        "onError": "#690005",
        "errorContainer": "#93000A",
        "onErrorContainer": "#FFDAD6",
        "background": "#151218",
        "onBackground": "#E7E0E8",
        "surface": "#151218",
        "onSurface": "#E7E0E8",
        "surfaceVariant": "#49454E",
        "onSurfaceVariant": "#CBC4CF",
        "outline": "#948F99",
        "outlineVariant": "#49454E",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#E7E0E8",
        "inverseOnSurface": "#322F35",
        "inversePrimary": "#79659F",
        "primaryFixed": "#EBDDFF",
        "onPrimaryFixed": "#230F46",
        "primaryFixedDim": "#D3BCFD",
        "onPrimaryFixedVariant": "#4F3D74",
        "secondaryFixed": "#E9DEF8",
        "onSecondaryFixed": "#1F182B",
        "secondaryFixedDim": "#CDC2DB",
        "onSecondaryFixedVariant": "#4B4358",
        "tertiaryFixed": "#FFD9E1",
        "onTertiaryFixed": "#31101B",
        "tertiaryFixedDim": "#F0B7C5",
        "onTertiaryFixedVariant": "#643B46",
        "surfaceDim": "#151218",
        "surfaceBright": "#3B383E",
        "surfaceContainerLowest": "#0F0D13",
        "surfaceContainerLow": "#1D1B20",
        "surfaceContainer": "#211F24",
        "surfaceContainerHigh": "#2C292F",
        "surfaceContainerHighest": "#36343A",
        "statusPlanned": "#999999",
        "statusPaid": "#67B533",
        "statusDone": "#EAAB00",
        "onStatusPlanned": "#111111",
        "onStatusPaid": "#DDDDDD",
        "onStatusDone": "#DDDDDD"
    }
}